// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: MobileSuiteV3.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_TYPE_UNKNOW                      MessageType = 0
	MessageType_MSG_TYPE_CHAT_MESSGAE_REQ            MessageType = 1 // 聊天信息:消息体为ChatMsg
	MessageType_MSG_TYPE_CHAT_MESSAGE_RES            MessageType = 2
	MessageType_MSG_TYPE_SEARCH_A_GAME_REQ           MessageType = 3 // 开始寻找一局游戏:消息体为玩家的昵称
	MessageType_MSG_TYPE_SEARCH_A_GAME_RES           MessageType = 4 // 开始搜寻的返回:0为成功; 非零失败;
	MessageType_MSG_TYPE_STOP_SEARCH_REQ             MessageType = 5 // 放弃搜寻游戏
	MessageType_MSG_TYPE_STOP_SEARCH_RES             MessageType = 6 // 放弃搜寻结果
	MessageType_MSG_TYPE_START_RES                   MessageType = 8 // 开始游戏:消息体为GameStartDTO
	MessageType_MSG_TYPE_LINE_A_POINT_REQ            MessageType = 9 // 连一个线
	MessageType_MSG_TYPE_LINE_A_POINT_RES            MessageType = 10
	MessageType_MSG_TYPE_LINE_A_POINT_TO_REQUEST_RES MessageType = 14
	MessageType_MSG_TYPE_END_GAME_REQ                MessageType = 11
	MessageType_MSG_TYPE_END_GAME_RES                MessageType = 12
	MessageType_MSG_TYPE_CREATE_USER_REQ             MessageType = 101 // 创建一个角色
	MessageType_MSG_TYPE_CREATE_USER_RES             MessageType = 102
	MessageType_MSG_TYPE_LOGIN_REQ                   MessageType = 103 // 登陆
	MessageType_MSG_TYPE_LOGIN_RES                   MessageType = 104
	MessageType_MSG_TYPE_LOGOUT_REQ                  MessageType = 105 // 登出
	MessageType_MSG_TYPE_LOGOUT_RES                  MessageType = 106
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_TYPE_UNKNOW",
		1:   "MSG_TYPE_CHAT_MESSGAE_REQ",
		2:   "MSG_TYPE_CHAT_MESSAGE_RES",
		3:   "MSG_TYPE_SEARCH_A_GAME_REQ",
		4:   "MSG_TYPE_SEARCH_A_GAME_RES",
		5:   "MSG_TYPE_STOP_SEARCH_REQ",
		6:   "MSG_TYPE_STOP_SEARCH_RES",
		8:   "MSG_TYPE_START_RES",
		9:   "MSG_TYPE_LINE_A_POINT_REQ",
		10:  "MSG_TYPE_LINE_A_POINT_RES",
		14:  "MSG_TYPE_LINE_A_POINT_TO_REQUEST_RES",
		11:  "MSG_TYPE_END_GAME_REQ",
		12:  "MSG_TYPE_END_GAME_RES",
		101: "MSG_TYPE_CREATE_USER_REQ",
		102: "MSG_TYPE_CREATE_USER_RES",
		103: "MSG_TYPE_LOGIN_REQ",
		104: "MSG_TYPE_LOGIN_RES",
		105: "MSG_TYPE_LOGOUT_REQ",
		106: "MSG_TYPE_LOGOUT_RES",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNKNOW":                      0,
		"MSG_TYPE_CHAT_MESSGAE_REQ":            1,
		"MSG_TYPE_CHAT_MESSAGE_RES":            2,
		"MSG_TYPE_SEARCH_A_GAME_REQ":           3,
		"MSG_TYPE_SEARCH_A_GAME_RES":           4,
		"MSG_TYPE_STOP_SEARCH_REQ":             5,
		"MSG_TYPE_STOP_SEARCH_RES":             6,
		"MSG_TYPE_START_RES":                   8,
		"MSG_TYPE_LINE_A_POINT_REQ":            9,
		"MSG_TYPE_LINE_A_POINT_RES":            10,
		"MSG_TYPE_LINE_A_POINT_TO_REQUEST_RES": 14,
		"MSG_TYPE_END_GAME_REQ":                11,
		"MSG_TYPE_END_GAME_RES":                12,
		"MSG_TYPE_CREATE_USER_REQ":             101,
		"MSG_TYPE_CREATE_USER_RES":             102,
		"MSG_TYPE_LOGIN_REQ":                   103,
		"MSG_TYPE_LOGIN_RES":                   104,
		"MSG_TYPE_LOGOUT_REQ":                  105,
		"MSG_TYPE_LOGOUT_RES":                  106,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_MobileSuiteV3_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_MobileSuiteV3_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{0}
}

type MobileSuiteModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MobileSuiteModel) Reset() {
	*x = MobileSuiteModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobileSuiteModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileSuiteModel) ProtoMessage() {}

func (x *MobileSuiteModel) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileSuiteModel.ProtoReflect.Descriptor instead.
func (*MobileSuiteModel) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{0}
}

func (x *MobileSuiteModel) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MobileSuiteModel) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// 聊天信息对应消息体
type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatType    int32  `protobuf:"varint,1,opt,name=chatType,proto3" json:"chatType,omitempty"`
	UserId      int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UName       string `protobuf:"bytes,3,opt,name=uName,proto3" json:"uName,omitempty"`
	ChatContext string `protobuf:"bytes,4,opt,name=chatContext,proto3" json:"chatContext,omitempty"`
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMsg) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *ChatMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatMsg) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *ChatMsg) GetChatContext() string {
	if x != nil {
		return x.ChatContext
	}
	return ""
}

// 开始游戏的信息消息体
type GameStartDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpptName    string `protobuf:"bytes,1,opt,name=opptName,proto3" json:"opptName,omitempty"`        // 对手昵称
	PlayerIndex int32  `protobuf:"varint,2,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"` // 玩家的先后手
}

func (x *GameStartDTO) Reset() {
	*x = GameStartDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartDTO) ProtoMessage() {}

func (x *GameStartDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartDTO.ProtoReflect.Descriptor instead.
func (*GameStartDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{2}
}

func (x *GameStartDTO) GetOpptName() string {
	if x != nil {
		return x.OpptName
	}
	return ""
}

func (x *GameStartDTO) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

// 连一个线
type LineAPointDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row         int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col         int32 `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	PlayerIndex int32 `protobuf:"varint,3,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
}

func (x *LineAPointDTO) Reset() {
	*x = LineAPointDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineAPointDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineAPointDTO) ProtoMessage() {}

func (x *LineAPointDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineAPointDTO.ProtoReflect.Descriptor instead.
func (*LineAPointDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{3}
}

func (x *LineAPointDTO) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *LineAPointDTO) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *LineAPointDTO) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

// 连线的返回值
type LineAPointResponseDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *LineAPointResponseDTO) Reset() {
	*x = LineAPointResponseDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineAPointResponseDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineAPointResponseDTO) ProtoMessage() {}

func (x *LineAPointResponseDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineAPointResponseDTO.ProtoReflect.Descriptor instead.
func (*LineAPointResponseDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{4}
}

func (x *LineAPointResponseDTO) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 创建角色
type CreateUserDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UName string `protobuf:"bytes,1,opt,name=uName,proto3" json:"uName,omitempty"`
	Pwd   string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *CreateUserDTO) Reset() {
	*x = CreateUserDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDTO) ProtoMessage() {}

func (x *CreateUserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDTO.ProtoReflect.Descriptor instead.
func (*CreateUserDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserDTO) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *CreateUserDTO) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

// 创建角色返回
type CreateResultDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CreateResultDTO) Reset() {
	*x = CreateResultDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResultDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResultDTO) ProtoMessage() {}

func (x *CreateResultDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResultDTO.ProtoReflect.Descriptor instead.
func (*CreateResultDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResultDTO) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 登陆
type LoginDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UName  string `protobuf:"bytes,2,opt,name=uName,proto3" json:"uName,omitempty"`
	Pwd    string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *LoginDTO) Reset() {
	*x = LoginDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDTO) ProtoMessage() {}

func (x *LoginDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDTO.ProtoReflect.Descriptor instead.
func (*LoginDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{7}
}

func (x *LoginDTO) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginDTO) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *LoginDTO) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

// 登陆返回
type LoginResultDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UName    string `protobuf:"bytes,2,opt,name=uName,proto3" json:"uName,omitempty"`
	Round    int32  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	WinCount int32  `protobuf:"varint,4,opt,name=winCount,proto3" json:"winCount,omitempty"`
	Rank     int32  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *LoginResultDTO) Reset() {
	*x = LoginResultDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResultDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResultDTO) ProtoMessage() {}

func (x *LoginResultDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResultDTO.ProtoReflect.Descriptor instead.
func (*LoginResultDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResultDTO) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResultDTO) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *LoginResultDTO) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *LoginResultDTO) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *LoginResultDTO) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 退出登陆
type LogoutDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LogoutDTO) Reset() {
	*x = LogoutDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MobileSuiteV3_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutDTO) ProtoMessage() {}

func (x *LogoutDTO) ProtoReflect() protoreflect.Message {
	mi := &file_MobileSuiteV3_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutDTO.ProtoReflect.Descriptor instead.
func (*LogoutDTO) Descriptor() ([]byte, []int) {
	return file_MobileSuiteV3_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutDTO) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_MobileSuiteV3_proto protoreflect.FileDescriptor

var file_MobileSuiteV3_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x53, 0x75, 0x69, 0x74, 0x65, 0x56, 0x33, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22,
	0x40, 0x0a, 0x10, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x53, 0x75, 0x69, 0x74, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x75, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x70, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x70, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x55, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x65, 0x41, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2f, 0x0a,
	0x15, 0x4c, 0x69, 0x6e, 0x65, 0x41, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x54, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x37,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x54, 0x4f, 0x12,
	0x14, 0x0a, 0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x54, 0x4f, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x84,
	0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x54,
	0x4f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x23, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x44,
	0x54, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x2a, 0xb0, 0x04, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x53,
	0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12,
	0x1d, 0x0a, 0x19, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54,
	0x5f, 0x4d, 0x45, 0x53, 0x53, 0x47, 0x41, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x1d,
	0x0a, 0x19, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x02, 0x12, 0x1e, 0x0a,
	0x1a, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48,
	0x5f, 0x41, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x1e, 0x0a,
	0x1a, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48,
	0x5f, 0x41, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x04, 0x12, 0x1c, 0x0a,
	0x18, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x53,
	0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x1c, 0x0a, 0x18, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x45, 0x41,
	0x52, 0x43, 0x48, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10,
	0x08, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49,
	0x4e, 0x45, 0x5f, 0x41, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x09,
	0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49, 0x4e,
	0x45, 0x5f, 0x41, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0a, 0x12,
	0x28, 0x0a, 0x24, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49, 0x4e, 0x45,
	0x5f, 0x41, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0e, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52,
	0x45, 0x51, 0x10, 0x0b, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0c, 0x12,
	0x1c, 0x0a, 0x18, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x65, 0x12, 0x1c, 0x0a,
	0x18, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x66, 0x12, 0x16, 0x0a, 0x12, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x67, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x68, 0x12, 0x17, 0x0a, 0x13, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x5f, 0x52,
	0x45, 0x51, 0x10, 0x69, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x6a, 0x42, 0x14, 0x5a,
	0x12, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MobileSuiteV3_proto_rawDescOnce sync.Once
	file_MobileSuiteV3_proto_rawDescData = file_MobileSuiteV3_proto_rawDesc
)

func file_MobileSuiteV3_proto_rawDescGZIP() []byte {
	file_MobileSuiteV3_proto_rawDescOnce.Do(func() {
		file_MobileSuiteV3_proto_rawDescData = protoimpl.X.CompressGZIP(file_MobileSuiteV3_proto_rawDescData)
	})
	return file_MobileSuiteV3_proto_rawDescData
}

var file_MobileSuiteV3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MobileSuiteV3_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_MobileSuiteV3_proto_goTypes = []interface{}{
	(MessageType)(0),              // 0: protocol.MessageType
	(*MobileSuiteModel)(nil),      // 1: protocol.MobileSuiteModel
	(*ChatMsg)(nil),               // 2: protocol.ChatMsg
	(*GameStartDTO)(nil),          // 3: protocol.GameStartDTO
	(*LineAPointDTO)(nil),         // 4: protocol.LineAPointDTO
	(*LineAPointResponseDTO)(nil), // 5: protocol.LineAPointResponseDTO
	(*CreateUserDTO)(nil),         // 6: protocol.CreateUserDTO
	(*CreateResultDTO)(nil),       // 7: protocol.CreateResultDTO
	(*LoginDTO)(nil),              // 8: protocol.LoginDTO
	(*LoginResultDTO)(nil),        // 9: protocol.LoginResultDTO
	(*LogoutDTO)(nil),             // 10: protocol.LogoutDTO
}
var file_MobileSuiteV3_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MobileSuiteV3_proto_init() }
func file_MobileSuiteV3_proto_init() {
	if File_MobileSuiteV3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MobileSuiteV3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobileSuiteModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineAPointDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineAPointResponseDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResultDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResultDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MobileSuiteV3_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MobileSuiteV3_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MobileSuiteV3_proto_goTypes,
		DependencyIndexes: file_MobileSuiteV3_proto_depIdxs,
		EnumInfos:         file_MobileSuiteV3_proto_enumTypes,
		MessageInfos:      file_MobileSuiteV3_proto_msgTypes,
	}.Build()
	File_MobileSuiteV3_proto = out.File
	file_MobileSuiteV3_proto_rawDesc = nil
	file_MobileSuiteV3_proto_goTypes = nil
	file_MobileSuiteV3_proto_depIdxs = nil
}
