// Code generated by protoc-gen-go.
// source: MobileSuite.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	MobileSuite.proto

It has these top-level messages:
	MobileSuiteModel
	ChatMsg
*/
package protocol

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MobileSuiteModel struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MobileSuiteModel) Reset()         { *m = MobileSuiteModel{} }
func (m *MobileSuiteModel) String() string { return proto.CompactTextString(m) }
func (*MobileSuiteModel) ProtoMessage()    {}

func (m *MobileSuiteModel) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MobileSuiteModel) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type ChatMsg struct {
	ChatContext      *string `protobuf:"bytes,1,req,name=chatContext" json:"chatContext,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}

func (m *ChatMsg) GetChatContext() string {
	if m != nil && m.ChatContext != nil {
		return *m.ChatContext
	}
	return ""
}

func init() {
}
