// Code generated by protoc-gen-go.
// source: MobileSuite.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	MobileSuite.proto

It has these top-level messages:
	MobileSuiteModel
	ChatMsg
	GameStartDTO
	LineAPointDTO
	CreateUserDTO
	CreateResultDTO
	LoginDTO
	LoginResultDTO
	LogoutDTO
*/
package protocol

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageType int32

const (
	MessageType_MSG_TYPE_CHAT_MESSGAE      MessageType = 1
	MessageType_MSG_TYPE_SEARCH_A_GAME_REQ MessageType = 3
	MessageType_MSG_TYPE_SEARCH_A_GAME_RES MessageType = 4
	MessageType_MSG_TYPE_STOP_SEARCH_REQ   MessageType = 5
	MessageType_MSG_TYPE_STOP_SEARCH_RES   MessageType = 6
	MessageType_MSG_TYPE_START_RES         MessageType = 8
	MessageType_MSG_TYPE_LINE_A_POINT_REQ  MessageType = 9
	MessageType_MSG_TYPE_LINE_A_POINT_RES  MessageType = 10
	MessageType_MSG_TYPE_END_GAME_REQ      MessageType = 11
	MessageType_MSG_TYPE_CREATE_USER_REQ   MessageType = 101
	MessageType_MSG_TYPE_CREATE_USER_RES   MessageType = 102
	MessageType_MSG_TYPE_LOGIN_REQ         MessageType = 103
	MessageType_MSG_TYPE_LOGIN_RES         MessageType = 104
)

var MessageType_name = map[int32]string{
	1:   "MSG_TYPE_CHAT_MESSGAE",
	3:   "MSG_TYPE_SEARCH_A_GAME_REQ",
	4:   "MSG_TYPE_SEARCH_A_GAME_RES",
	5:   "MSG_TYPE_STOP_SEARCH_REQ",
	6:   "MSG_TYPE_STOP_SEARCH_RES",
	8:   "MSG_TYPE_START_RES",
	9:   "MSG_TYPE_LINE_A_POINT_REQ",
	10:  "MSG_TYPE_LINE_A_POINT_RES",
	11:  "MSG_TYPE_END_GAME_REQ",
	101: "MSG_TYPE_CREATE_USER_REQ",
	102: "MSG_TYPE_CREATE_USER_RES",
	103: "MSG_TYPE_LOGIN_REQ",
	104: "MSG_TYPE_LOGIN_RES",
}
var MessageType_value = map[string]int32{
	"MSG_TYPE_CHAT_MESSGAE":      1,
	"MSG_TYPE_SEARCH_A_GAME_REQ": 3,
	"MSG_TYPE_SEARCH_A_GAME_RES": 4,
	"MSG_TYPE_STOP_SEARCH_REQ":   5,
	"MSG_TYPE_STOP_SEARCH_RES":   6,
	"MSG_TYPE_START_RES":         8,
	"MSG_TYPE_LINE_A_POINT_REQ":  9,
	"MSG_TYPE_LINE_A_POINT_RES":  10,
	"MSG_TYPE_END_GAME_REQ":      11,
	"MSG_TYPE_CREATE_USER_REQ":   101,
	"MSG_TYPE_CREATE_USER_RES":   102,
	"MSG_TYPE_LOGIN_REQ":         103,
	"MSG_TYPE_LOGIN_RES":         104,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

type MobileSuiteModel struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MobileSuiteModel) Reset()         { *m = MobileSuiteModel{} }
func (m *MobileSuiteModel) String() string { return proto.CompactTextString(m) }
func (*MobileSuiteModel) ProtoMessage()    {}

func (m *MobileSuiteModel) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MobileSuiteModel) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type ChatMsg struct {
	ChatContext      *string `protobuf:"bytes,1,req,name=chatContext" json:"chatContext,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}

func (m *ChatMsg) GetChatContext() string {
	if m != nil && m.ChatContext != nil {
		return *m.ChatContext
	}
	return ""
}

type GameStartDTO struct {
	OpptName         *string `protobuf:"bytes,1,req,name=opptName" json:"opptName,omitempty"`
	PlayerIndex      *int32  `protobuf:"varint,2,req,name=playerIndex" json:"playerIndex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameStartDTO) Reset()         { *m = GameStartDTO{} }
func (m *GameStartDTO) String() string { return proto.CompactTextString(m) }
func (*GameStartDTO) ProtoMessage()    {}

func (m *GameStartDTO) GetOpptName() string {
	if m != nil && m.OpptName != nil {
		return *m.OpptName
	}
	return ""
}

func (m *GameStartDTO) GetPlayerIndex() int32 {
	if m != nil && m.PlayerIndex != nil {
		return *m.PlayerIndex
	}
	return 0
}

type LineAPointDTO struct {
	Row              *int32 `protobuf:"varint,1,req,name=row" json:"row,omitempty"`
	Col              *int32 `protobuf:"varint,2,req,name=col" json:"col,omitempty"`
	PlayerIndex      *int32 `protobuf:"varint,3,req,name=playerIndex" json:"playerIndex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LineAPointDTO) Reset()         { *m = LineAPointDTO{} }
func (m *LineAPointDTO) String() string { return proto.CompactTextString(m) }
func (*LineAPointDTO) ProtoMessage()    {}

func (m *LineAPointDTO) GetRow() int32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *LineAPointDTO) GetCol() int32 {
	if m != nil && m.Col != nil {
		return *m.Col
	}
	return 0
}

func (m *LineAPointDTO) GetPlayerIndex() int32 {
	if m != nil && m.PlayerIndex != nil {
		return *m.PlayerIndex
	}
	return 0
}

type CreateUserDTO struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateUserDTO) Reset()         { *m = CreateUserDTO{} }
func (m *CreateUserDTO) String() string { return proto.CompactTextString(m) }
func (*CreateUserDTO) ProtoMessage()    {}

func (m *CreateUserDTO) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type CreateResultDTO struct {
	UserId           *int64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateResultDTO) Reset()         { *m = CreateResultDTO{} }
func (m *CreateResultDTO) String() string { return proto.CompactTextString(m) }
func (*CreateResultDTO) ProtoMessage()    {}

func (m *CreateResultDTO) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type LoginDTO struct {
	UserId           *int64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginDTO) Reset()         { *m = LoginDTO{} }
func (m *LoginDTO) String() string { return proto.CompactTextString(m) }
func (*LoginDTO) ProtoMessage()    {}

func (m *LoginDTO) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type LoginResultDTO struct {
	UserId           *int64  `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Round            *int32  `protobuf:"varint,3,req" json:"Round,omitempty"`
	WinCount         *int32  `protobuf:"varint,4,req" json:"WinCount,omitempty"`
	Rank             *int32  `protobuf:"varint,5,req" json:"Rank,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginResultDTO) Reset()         { *m = LoginResultDTO{} }
func (m *LoginResultDTO) String() string { return proto.CompactTextString(m) }
func (*LoginResultDTO) ProtoMessage()    {}

func (m *LoginResultDTO) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *LoginResultDTO) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LoginResultDTO) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *LoginResultDTO) GetWinCount() int32 {
	if m != nil && m.WinCount != nil {
		return *m.WinCount
	}
	return 0
}

func (m *LoginResultDTO) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

type LogoutDTO struct {
	UserId           *int64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LogoutDTO) Reset()         { *m = LogoutDTO{} }
func (m *LogoutDTO) String() string { return proto.CompactTextString(m) }
func (*LogoutDTO) ProtoMessage()    {}

func (m *LogoutDTO) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.MessageType", MessageType_name, MessageType_value)
}
